{"uuid": "5935e6d6-d48d-4c76-9712-278d1a46ce08", "children": ["ca5ed895-52fe-4d88-91dc-89e8f76481ba"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: create container: Error response from daemon: No such image: selenoid/firefox:108.0\n\n", "trace": "  File \"/Users/user/Documents/auto-web-qa/homework11/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/user/Documents/auto-web-qa/homework11/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/user/Documents/auto-web-qa/homework11/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/user/Documents/auto-web-qa/homework11/conftest.py\", line 109, in browser\n    driver = webdriver.Remote(\n  File \"/Users/user/Documents/auto-web-qa/homework11/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/user/Documents/auto-web-qa/homework11/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/user/Documents/auto-web-qa/homework11/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/user/Documents/auto-web-qa/homework11/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1676576362510, "stop": 1676576362540}], "start": 1676576362510, "stop": 1676576362600}